# Generated by Django 5.2.3 on 2025-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tries_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishsession',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
